;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Event.Combat.TurnStarted",DevComment="")
+GameplayTagList=(Tag="exterior",DevComment="")
+GameplayTagList=(Tag="interior",DevComment="")
+GameplayTagList=(Tag="interior.crypt01",DevComment="")
+GameplayTagList=(Tag="interior.crypt02",DevComment="")
+GameplayTagList=(Tag="interior.crypt03",DevComment="")
+GameplayTagList=(Tag="interior.crypt04",DevComment="")
+GameplayTagList=(Tag="interior.crypt05",DevComment="")
+GameplayTagList=(Tag="SoundScape.Environment",DevComment="")
+GameplayTagList=(Tag="SoundScape.Exterior",DevComment="")
+GameplayTagList=(Tag="SoundScape.Interior",DevComment="")

