;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="Buff.ArmorClass",DevComment="")
+GameplayTagList=(Tag="Buff.AttackBonus",DevComment="")
+GameplayTagList=(Tag="Debuff.ArmorClass.Hex",DevComment="")
+GameplayTagList=(Tag="Debuff.AttackBonus",DevComment="")
+GameplayTagList=(Tag="Debuff.SaveDC",DevComment="")
+GameplayTagList=(Tag="Event.Combat.TurnStarted",DevComment="")
+GameplayTagList=(Tag="exterior",DevComment="")
+GameplayTagList=(Tag="interior",DevComment="")
+GameplayTagList=(Tag="SoundScape.Environment",DevComment="")
+GameplayTagList=(Tag="SoundScape.Exterior",DevComment="")
+GameplayTagList=(Tag="SoundScape.Interior",DevComment="")

